version: '3'

services:
  api:
    build:
      context: .
    entrypoint: npm start
    env_file: .env
    depends_on:
      - postgres
    ports:
      - 5000:5000

  postgres:
    image: postgres
    ports:
      - 5432:5432
    env_file: .env.db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    external:
      name: postgres-data
